import { describe, it, expect } from 'vitest'
import { ResourceManager } from '../core/resource-manager'
import { CacheManager } from '../core/cache-manager'
import { EventBus } from '../core/event-bus'
import { AudioResources } from '../resources/audio-resources'
import { ImageResources } from '../resources/image-resources'
import { ErrorHandler } from '../core/error-handler'
import { ResourceLoader } from '../resources/resource-loader'

function createResourceManager() {
  const audioRegistry = new AudioResources()
  const imageRegistry = new ImageResources()
  const cache = new CacheManager(10, 60000, 50)
  const errorHandler = new ErrorHandler()
  const loader = new ResourceLoader(errorHandler, 4)
  const bus = new EventBus()

  audioRegistry.initialize()
  imageRegistry.initialize()

  return new ResourceManager(audioRegistry, imageRegistry, cache, loader, bus)
}

describe('ResourceManager', () => {
  it('should resolve audio paths', () => {
    const rm = createResourceManager()
    const path = rm.getAudioPath('correct')

    expect(path).not.toBeNull()
    expect(path).toContain('/audio')
  })

  it('should return null for unknown audio', () => {
    const rm = createResourceManager()
    expect(rm.getAudioPath('nonexistent')).toBeNull()
  })

  it('should resolve game letter audio keys generated by the API seed', () => {
    const rm = createResourceManager()

    expect(rm.getAudioPath('en-letter-q')).toBe('/audio/en/letter/q.mp3')
    expect(rm.getAudioPath('en-number-7')).toBe('/audio/en/number/7.mp3')
  })

  it('should resolve image paths', () => {
    const rm = createResourceManager()
    const path = rm.getImagePath('letter-a')

    expect(path).not.toBeNull()
    expect(path).toContain('/assets/images/letters')
  })

  it('should return null for unknown images', () => {
    const rm = createResourceManager()
    expect(rm.getImagePath('nonexistent')).toBeNull()
  })

  it('should check audio existence', () => {
    const rm = createResourceManager()
    expect(rm.hasAudio('correct')).toBe(true)
    expect(rm.hasAudio('missing')).toBe(false)
  })

  it('should check image existence', () => {
    const rm = createResourceManager()
    expect(rm.hasImage('letter-a')).toBe(true)
    expect(rm.hasImage('missing')).toBe(false)
  })

  it('should support language-aware paths', () => {
    const rm = createResourceManager()
    rm.setLanguage('es')
    const path = rm.getAudioPath('correct')

    expect(path).toContain('/es/')
  })

  it('should list all audio keys', () => {
    const rm = createResourceManager()
    const keys = rm.getAllAudioKeys()
    expect(keys.length).toBeGreaterThan(0)
    expect(keys).toContain('correct')
    expect(keys).toContain('click')
    expect(keys).toContain('theme')
  })

  it('should filter audio by category', () => {
    const rm = createResourceManager()
    const sfxList = rm.getAllAudioByCategory('sfx')
    expect(sfxList.length).toBeGreaterThan(0)
    expect(sfxList.every((r) => r.category === 'sfx')).toBe(true)
  })

  it('should register custom audio', () => {
    const rm = createResourceManager()
    rm.registerAudio({
      key: 'custom-test',
      category: 'sfx',
      subcategory: 'effects',
      path: '/custom/test.mp3',
    })

    expect(rm.hasAudio('custom-test')).toBe(true)
    expect(rm.getAudioPath('custom-test')).toBe('/custom/test.mp3')
  })

  it('should register custom images', () => {
    const rm = createResourceManager()
    rm.registerImage({
      key: 'custom-img',
      path: '/custom/img.svg',
    })

    expect(rm.hasImage('custom-img')).toBe(true)
    expect(rm.getImagePath('custom-img')).toBe('/custom/img.svg')
  })

  it('should return cache stats', () => {
    const rm = createResourceManager()
    const stats = rm.getCacheStats()
    expect(stats).toHaveProperty('hits')
    expect(stats).toHaveProperty('misses')
    expect(stats).toHaveProperty('entries')
  })
})
