import type { AudioResourceDefinition, Language } from '../types'

type AudioRegistry = Map<string, AudioResourceDefinition>

const API_BASE = '/audio'

const LETTERS = 'abcdefghijklmnopqrstuvwxyz'.split('')
const NUMBERS = Array.from({ length: 10 }, (_, number) => String(number))

const INSTRUCTION_KEYS = [
  'press-first-letter',
  'press-number',
  'what-letter',
  'find-the-letter',
  'repeat-after-me',
  'listen-and-type',
]

const FEEDBACK_KEYS = [
  'correct',
  'wrong',
  'excellent',
  'great-job',
  'amazing',
  'try-again',
  'congratulations',
]

const EFFECT_KEYS = [
  'click',
  'hover',
  'success',
  'failure',
  'level-complete',
  'achievement',
  'countdown',
  'game-over',
]

const MUSIC_KEYS = [
  'theme',
  'gameplay',
  'victory',
]

export class AudioResources {
  private registry: AudioRegistry = new Map()
  private initialized = false

  initialize(baseUrl = API_BASE): void {
    if (this.initialized) return

    this.registerInstructions(baseUrl)
    this.registerFeedback(baseUrl)
    this.registerEffects(baseUrl)
    this.registerMusic(baseUrl)
    this.registerGameContent(baseUrl)

    this.initialized = true
  }

  get(key: string): AudioResourceDefinition | undefined {
    return this.registry.get(key)
  }

  has(key: string): boolean {
    return this.registry.has(key)
  }

  getByCategory(category: string): AudioResourceDefinition[] {
    return Array.from(this.registry.values()).filter((r) => r.category === category)
  }

  getBySubcategory(subcategory: string): AudioResourceDefinition[] {
    return Array.from(this.registry.values()).filter((r) => r.subcategory === subcategory)
  }

  getAll(): AudioResourceDefinition[] {
    return Array.from(this.registry.values())
  }

  getKeys(): string[] {
    return Array.from(this.registry.keys())
  }

  resolvePath(key: string, language?: Language): string | null {
    const resource = this.registry.get(key)
    if (!resource) return null

    if (resource.subcategory === 'instructions' || resource.subcategory === 'feedback') {
      const lang = language ?? 'en'
      return resource.path.replace('{lang}', lang)
    }

    return resource.path
  }

  registerCustom(def: AudioResourceDefinition): void {
    this.registry.set(def.key, def)
  }

  private registerInstructions(baseUrl: string): void {
    for (const key of INSTRUCTION_KEYS) {
      this.registry.set(key, {
        key,
        category: 'voice',
        subcategory: 'instructions',
        path: `${baseUrl}/instructions/{lang}/${key}`,
      })
    }
  }

  private registerFeedback(baseUrl: string): void {
    for (const key of FEEDBACK_KEYS) {
      this.registry.set(key, {
        key,
        category: 'voice',
        subcategory: 'feedback',
        path: `${baseUrl}/feedback/{lang}/${key}`,
      })
    }
  }

  private registerEffects(baseUrl: string): void {
    for (const key of EFFECT_KEYS) {
      this.registry.set(key, {
        key,
        category: 'sfx',
        subcategory: 'effects',
        path: `${baseUrl}/effects/${key}`,
      })
    }
  }

  private registerMusic(baseUrl: string): void {
    for (const key of MUSIC_KEYS) {
      this.registry.set(key, {
        key,
        category: 'music',
        subcategory: 'music',
        path: `${baseUrl}/music/${key}`,
      })
    }
  }

  /**
   * Keys generated by the game seed, for example `en-letter-q`.
   * Audio files are served by Nest from `public/audio/<language>/<type>/`.
   */
  private registerGameContent(baseUrl: string): void {
    for (const letter of LETTERS) {
      this.registry.set(`en-letter-${letter}`, {
        key: `en-letter-${letter}`,
        category: 'voice',
        subcategory: 'content',
        path: `${baseUrl}/en/letter/${letter}.mp3`,
      })
    }

    for (const number of NUMBERS) {
      this.registry.set(`en-number-${number}`, {
        key: `en-number-${number}`,
        category: 'voice',
        subcategory: 'content',
        path: `${baseUrl}/en/number/${number}.mp3`,
      })
    }
  }

  reset(): void {
    this.registry.clear()
    this.initialized = false
  }
}

export const audioResources = new AudioResources()
